import type { FileToolId, ToolCategory, ToolDefinition, ToolId } from './types'

export const categoryOrder: ToolCategory[] = ['image', 'pdf', 'document', 'presentation', 'archive', 'data', 'utility']

export const categoryCopy: Record<
  ToolCategory,
  { title: { en: string; zh: string }; description: { en: string; zh: string } }
> = {
  image: {
    title: { en: 'Image tools', zh: '图片工具' },
    description: {
      en: 'Compress, convert, resize, rotate, and flip images.',
      zh: '压缩、转换、调整尺寸、旋转和翻转图片。',
    },
  },
  pdf: {
    title: { en: 'PDF tools', zh: 'PDF 工具' },
    description: {
      en: 'Organize pages and create PDFs without uploading files.',
      zh: '无需上传即可整理页面和创建 PDF。',
    },
  },
  document: {
    title: { en: 'Document tools', zh: '文档工具' },
    description: {
      en: 'Convert DOCX content and create simple Word documents.',
      zh: '转换 DOCX 内容并创建简洁的 Word 文档。',
    },
  },
  presentation: {
    title: { en: 'Presentation tools', zh: '演示文稿工具' },
    description: { en: 'Create editable PPTX files from images or text.', zh: '从图片或文本创建可编辑的 PPTX 文件。' },
  },
  archive: {
    title: { en: 'Archive tools', zh: '压缩包工具' },
    description: { en: 'Create and inspect ZIP archives locally.', zh: '在本地创建和解压 ZIP 压缩包。' },
  },
  data: {
    title: { en: 'Data tools', zh: '数据工具' },
    description: { en: 'Format JSON and convert CSV data.', zh: '格式化 JSON 并转换 CSV 数据。' },
  },
  utility: {
    title: { en: 'File utilities', zh: '文件实用工具' },
    description: { en: 'Calculate checksums and work with Base64.', zh: '计算文件校验值并处理 Base64。' },
  },
}

export const tools: ToolDefinition[] = [
  {
    id: 'word-to-pdf',
    category: 'pdf',
    path: '/tools/pdf/word-to-pdf',
    badge: 'DOCX → PDF',
    input: 'files',
    accept: '.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    title: { en: 'Word to PDF', zh: 'Word 转 PDF' },
    description: {
      en: 'Render DOCX pages into a downloadable PDF, privately.',
      zh: '本地渲染 DOCX 页面，生成可下载的 PDF。',
    },
    action: { en: 'Convert to PDF', zh: '转换为 PDF' },
  },
  {
    id: 'pdf-to-word',
    category: 'pdf',
    path: '/tools/pdf/to-word',
    badge: 'PDF → DOCX',
    input: 'files',
    accept: '.pdf,application/pdf',
    title: { en: 'PDF to Word', zh: 'PDF 转 Word' },
    description: {
      en: 'Export editable text or preserve page appearance in DOCX.',
      zh: '导出可编辑文字，或以页面图片保留外观，生成 DOCX。',
    },
    action: { en: 'Convert to Word', zh: '转换为 Word' },
  },
  {
    id: 'pdf-to-images',
    category: 'pdf',
    path: '/tools/pdf/to-images',
    badge: 'PDF → JPG',
    input: 'files',
    accept: '.pdf,application/pdf',
    title: { en: 'PDF to JPG', zh: 'PDF 转图片' },
    description: {
      en: 'Save selected PDF pages as JPG images in a ZIP file.',
      zh: '将选定的 PDF 页面转为 JPG 图片，打包下载。',
    },
    action: { en: 'Convert to images', zh: '转换为图片' },
  },
  {
    id: 'pdf-to-text',
    category: 'pdf',
    path: '/tools/pdf/to-text',
    badge: 'PDF → TXT',
    input: 'files',
    accept: '.pdf,application/pdf',
    title: { en: 'PDF to text', zh: 'PDF 转文本' },
    description: {
      en: 'Extract selectable PDF text into a UTF-8 text file.',
      zh: '提取 PDF 中可选择的文字，保存为 UTF-8 文本文件。',
    },
    action: { en: 'Extract text', zh: '提取文字' },
  },
  {
    id: 'image-compress',
    category: 'image',
    path: '/tools/image/compress',
    badge: 'IMG',
    input: 'files',
    multiple: true,
    accept: 'image/jpeg,image/png,image/webp',
    title: { en: 'Compress images', zh: '图片压缩' },
    description: { en: 'Reduce JPG, PNG, and WebP file sizes.', zh: '减小 JPG、PNG 和 WebP 文件体积。' },
    action: { en: 'Open image studio', zh: '打开图片工作台' },
  },
  {
    id: 'image-convert',
    category: 'image',
    path: '/tools/image/convert',
    badge: 'IMG',
    input: 'files',
    multiple: true,
    accept: 'image/jpeg,image/png,image/webp',
    title: { en: 'Convert image format', zh: '图片格式转换' },
    description: { en: 'Convert between JPG, PNG, and WebP.', zh: '在 JPG、PNG 和 WebP 之间转换。' },
    action: { en: 'Open image studio', zh: '打开图片工作台' },
  },
  {
    id: 'image-resize',
    category: 'image',
    path: '/tools/image/resize',
    badge: 'IMG',
    input: 'files',
    multiple: true,
    accept: 'image/jpeg,image/png,image/webp',
    title: { en: 'Resize images', zh: '图片尺寸调整' },
    description: { en: 'Resize image width while preserving proportions.', zh: '按比例调整图片宽度。' },
    action: { en: 'Open image studio', zh: '打开图片工作台' },
  },
  {
    id: 'image-rotate',
    category: 'image',
    path: '/tools/image/rotate',
    badge: 'IMG',
    input: 'files',
    multiple: true,
    accept: 'image/jpeg,image/png,image/webp',
    title: { en: 'Rotate images', zh: '旋转图片' },
    description: { en: 'Rotate images by 90, 180, or 270 degrees.', zh: '将图片旋转 90、180 或 270 度。' },
    action: { en: 'Open image studio', zh: '打开图片工作台' },
  },
  {
    id: 'image-flip',
    category: 'image',
    path: '/tools/image/flip',
    badge: 'IMG',
    input: 'files',
    multiple: true,
    accept: 'image/jpeg,image/png,image/webp',
    title: { en: 'Flip images', zh: '翻转图片' },
    description: { en: 'Flip images horizontally or vertically.', zh: '水平或垂直翻转图片。' },
    action: { en: 'Open image studio', zh: '打开图片工作台' },
  },
  {
    id: 'pdf-merge',
    category: 'pdf',
    path: '/tools/pdf/merge',
    badge: 'PDF',
    input: 'files',
    multiple: true,
    accept: '.pdf,application/pdf',
    title: { en: 'Merge PDFs', zh: '合并 PDF' },
    description: { en: 'Combine multiple PDFs in your selected order.', zh: '按照选择顺序合并多个 PDF。' },
    action: { en: 'Merge PDFs', zh: '合并 PDF' },
  },
  {
    id: 'pdf-split',
    category: 'pdf',
    path: '/tools/pdf/split',
    badge: 'PDF',
    input: 'files',
    multiple: false,
    accept: '.pdf,application/pdf',
    title: { en: 'Split PDF', zh: '拆分 PDF' },
    description: { en: 'Create one PDF file for every page.', zh: '为每一页生成独立 PDF 文件。' },
    action: { en: 'Split PDF', zh: '拆分 PDF' },
  },
  {
    id: 'pdf-extract-pages',
    category: 'pdf',
    path: '/tools/pdf/extract-pages',
    badge: 'PDF',
    input: 'files',
    multiple: false,
    accept: '.pdf,application/pdf',
    title: { en: 'Extract PDF pages', zh: '提取 PDF 页面' },
    description: { en: 'Create a new PDF from selected page ranges.', zh: '从指定页码范围创建新的 PDF。' },
    action: { en: 'Extract pages', zh: '提取页面' },
  },
  {
    id: 'pdf-remove-pages',
    category: 'pdf',
    path: '/tools/pdf/remove-pages',
    badge: 'PDF',
    input: 'files',
    multiple: false,
    accept: '.pdf,application/pdf',
    title: { en: 'Remove PDF pages', zh: '删除 PDF 页面' },
    description: { en: 'Remove selected pages and save the remaining PDF.', zh: '删除指定页面并保存剩余内容。' },
    action: { en: 'Remove pages', zh: '删除页面' },
  },
  {
    id: 'pdf-rotate-pages',
    category: 'pdf',
    path: '/tools/pdf/rotate-pages',
    badge: 'PDF',
    input: 'files',
    multiple: false,
    accept: '.pdf,application/pdf',
    title: { en: 'Rotate PDF pages', zh: '旋转 PDF 页面' },
    description: { en: 'Rotate all pages or a selected page range.', zh: '旋转全部页面或指定页码范围。' },
    action: { en: 'Rotate pages', zh: '旋转页面' },
  },
  {
    id: 'images-to-pdf',
    category: 'pdf',
    path: '/tools/pdf/images-to-pdf',
    badge: 'PDF',
    input: 'files',
    multiple: true,
    accept: 'image/jpeg,image/png,image/webp',
    title: { en: 'Images to PDF', zh: '图片转 PDF' },
    description: { en: 'Create one PDF from multiple images.', zh: '将多张图片生成一个 PDF。' },
    action: { en: 'Create PDF', zh: '生成 PDF' },
  },
  {
    id: 'docx-to-html',
    category: 'document',
    path: '/tools/document/docx-to-html',
    badge: 'DOCX',
    input: 'files',
    multiple: false,
    accept: '.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    title: { en: 'DOCX to HTML', zh: 'Word 转 HTML' },
    description: {
      en: 'Extract headings, paragraphs, lists, and images as HTML.',
      zh: '将标题、段落、列表和图片提取为 HTML。',
    },
    action: { en: 'Convert to HTML', zh: '转换为 HTML' },
  },
  {
    id: 'docx-to-text',
    category: 'document',
    path: '/tools/document/docx-to-text',
    badge: 'TXT',
    input: 'files',
    multiple: false,
    accept: '.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    title: { en: 'DOCX to text', zh: 'Word 转文本' },
    description: { en: 'Extract readable plain text from a DOCX document.', zh: '从 DOCX 文档中提取可读纯文本。' },
    action: { en: 'Extract text', zh: '提取文本' },
  },
  {
    id: 'text-to-docx',
    category: 'document',
    path: '/tools/document/text-to-docx',
    badge: 'DOCX',
    input: 'text',
    title: { en: 'Text to DOCX', zh: '文本转 Word' },
    description: {
      en: 'Create a simple editable Word document from text.',
      zh: '将文本创建为简单、可编辑的 Word 文档。',
    },
    action: { en: 'Create DOCX', zh: '生成 DOCX' },
  },
  {
    id: 'images-to-pptx',
    category: 'presentation',
    path: '/tools/presentation/images-to-pptx',
    badge: 'PPTX',
    input: 'files',
    multiple: true,
    accept: 'image/jpeg,image/png,image/webp',
    title: { en: 'Images to PPTX', zh: '图片生成 PPT' },
    description: { en: 'Create one widescreen slide for every image.', zh: '每张图片生成一页宽屏幻灯片。' },
    action: { en: 'Create PPTX', zh: '生成 PPTX' },
  },
  {
    id: 'text-to-pptx',
    category: 'presentation',
    path: '/tools/presentation/text-to-pptx',
    badge: 'PPTX',
    input: 'text',
    title: { en: 'Text to PPTX', zh: '文本生成 PPT' },
    description: {
      en: 'Turn text sections into clean, editable slides.',
      zh: '将文本分段转换为简洁、可编辑的幻灯片。',
    },
    action: { en: 'Create PPTX', zh: '生成 PPTX' },
  },
  {
    id: 'zip-create',
    category: 'archive',
    path: '/tools/archive/create-zip',
    badge: 'ZIP',
    input: 'files',
    multiple: true,
    title: { en: 'Create ZIP', zh: '创建 ZIP' },
    description: { en: 'Package multiple files into one ZIP archive.', zh: '将多个文件打包成一个 ZIP 压缩包。' },
    action: { en: 'Create ZIP', zh: '创建 ZIP' },
  },
  {
    id: 'zip-extract',
    category: 'archive',
    path: '/tools/archive/extract-zip',
    badge: 'ZIP',
    input: 'files',
    multiple: false,
    accept: '.zip,application/zip,application/x-zip-compressed',
    title: { en: 'Extract ZIP', zh: '解压 ZIP' },
    description: { en: 'Inspect and download files from a ZIP archive.', zh: '查看并下载 ZIP 压缩包中的文件。' },
    action: { en: 'Extract ZIP', zh: '解压 ZIP' },
  },
  {
    id: 'json-format',
    category: 'data',
    path: '/tools/data/json-formatter',
    badge: 'JSON',
    input: 'text',
    title: { en: 'JSON formatter', zh: 'JSON 格式化' },
    description: { en: 'Validate, format, or minify JSON data.', zh: '校验、格式化或压缩 JSON 数据。' },
    action: { en: 'Format JSON', zh: '格式化 JSON' },
  },
  {
    id: 'csv-to-json',
    category: 'data',
    path: '/tools/data/csv-to-json',
    badge: 'CSV',
    input: 'files',
    multiple: false,
    accept: '.csv,text/csv,text/plain',
    title: { en: 'CSV to JSON', zh: 'CSV 转 JSON' },
    description: { en: 'Convert a CSV table into a JSON array.', zh: '将 CSV 表格转换为 JSON 数组。' },
    action: { en: 'Convert to JSON', zh: '转换为 JSON' },
  },
  {
    id: 'json-to-csv',
    category: 'data',
    path: '/tools/data/json-to-csv',
    badge: 'CSV',
    input: 'text',
    title: { en: 'JSON to CSV', zh: 'JSON 转 CSV' },
    description: { en: 'Convert an array of objects into a CSV table.', zh: '将对象数组转换为 CSV 表格。' },
    action: { en: 'Convert to CSV', zh: '转换为 CSV' },
  },
  {
    id: 'file-checksum',
    category: 'utility',
    path: '/tools/utility/checksum',
    badge: 'HASH',
    input: 'files',
    multiple: false,
    title: { en: 'File checksum', zh: '文件校验值' },
    description: {
      en: 'Calculate SHA-256, SHA-384, or SHA-512 locally.',
      zh: '在本地计算 SHA-256、SHA-384 或 SHA-512。',
    },
    action: { en: 'Calculate checksum', zh: '计算校验值' },
  },
  {
    id: 'file-to-base64',
    category: 'utility',
    path: '/tools/utility/file-to-base64',
    badge: 'B64',
    input: 'files',
    multiple: false,
    title: { en: 'File to Base64', zh: '文件转 Base64' },
    description: { en: 'Encode any file as a Base64 data URL.', zh: '将任意文件编码为 Base64 Data URL。' },
    action: { en: 'Encode file', zh: '编码文件' },
  },
  {
    id: 'base64-to-file',
    category: 'utility',
    path: '/tools/utility/base64-to-file',
    badge: 'FILE',
    input: 'base64',
    title: { en: 'Base64 to file', zh: 'Base64 转文件' },
    description: {
      en: 'Decode Base64 or a data URL into a downloadable file.',
      zh: '将 Base64 或 Data URL 解码为可下载文件。',
    },
    action: { en: 'Decode file', zh: '解码文件' },
  },
]

export const fileTools = tools.filter(
  (tool): tool is ToolDefinition & { id: FileToolId } => !tool.id.startsWith('image-'),
)

export function getTool(id: ToolId) {
  return tools.find((tool) => tool.id === id)
}

export function getToolByPath(path: string) {
  return tools.find((tool) => tool.path === path)
}
